#!/usr/bin/env python3

##############################
#  Needs to be run as root!  #
##############################

from appJar import gui
from subprocess import Popen
from SettingsRW import *


theme = getSetting("theme")
language = getSetting("language")

def LanguageHandler(press):
    if press == "English":
        setSetting("language", "english")
        with open("/etc/default/locale", "w") as file:
            file.write("#  File generated by update-locale\nLANG=en_GB.UTF-8\n")
        app.changeLanguage("english")

    elif press == "Español":
        setSetting("language", "spanish")
        with open("/etc/default/locale", "w") as file:
            file.write("#  File generated by update-locale\nLANG=es_ES.UTF-8\n")
        app.changeLanguage("spanish")

            
    if app.yesNoBox("Reboot", "You need to reboot your Solar Pi to apply these changes.\nWould you like to reboot now?") == True:
        Popen("/usr/local/bin/Solar Pi/Resources/Launchers/Reboot.sh")

with gui("Languages", useTtk=True) as app:
    app.setResizable(False)

    if theme == "Solar Pi":
        custom = True
        app.setTtkTheme("plastik")
        app.setTtkTheme("clam")
        #app.ttkStyle.configure(".", font="10", background="white")

        # Highlighted button
        app.ttkStyle.configure("H.TButton", background="#324581", foreground="white", bordercolor="#687396")
        app.ttkStyle.map("H.TButton", background=[("pressed", "#172141"), ("active", "#4059a9")])

        # Regular button
        app.ttkStyle.configure("TButton", background="#dbdce2", bordercolor="#687396")

        # LabelFrame colour
        app.ttkStyle.configure("TLabelframe", bordercolor="#687396")

        app.setBg("white")

    else:
        custom = False
        app.setTtkTheme(theme)
        if theme != "black":
            app.ttkStyle.configure(".", background="white", foreground="black")
            app.setBg("white")

    app.setPadding(5, 5)
    with app.labelFrame("Languages"):
        app.setPadding(5, 5)
        app.setSticky("nesw")

        with app.frame("language info"):
            app.ttkStyle.configure("H.TLabel", font=("piboto", 12, "bold"))
            app.addLabel("language_info", "The current language is:")

            app.addLabel("language", language[0].upper() + language[1:], 0, 1)
            app.setLabelSticky("language", "w")
            app.setLabelStyle("language", "H.TLabel")

        app.addLabel("info_english", "Click or tap on the button to change the language.\nPlease only change it if the current language is not suitable for you.")
        app.addLabel("info_spanish", "Haz clic o toca el botón para cambiar el idioma.\nCambie solo si el idioma actual no es adecuado para usted.")

        with app.frame("langauges"):
            with app.labelFrame("English", 0, 0):
                app.setPadding(5, 5)
                app.addImage("uk_flag", "../Resources/Images/uk_flag.gif")
                app.addButton("English", LanguageHandler, 0, 1)

            with app.labelFrame("Español", 0, 1):
                app.setPadding(5, 5)
                app.addImage("spain_flag", "../Resources/Images/spain_flag.gif")
                app.addButton("Español", LanguageHandler, 0, 1)

    if custom == False:
        app.setLabelFrameStyle("Languages", "TFrame")
        app.setLabelFrameStyle("English", "TFrame")
        app.setLabelFrameStyle("Español", "TFrame")