site_name: Solar Pi Docs

markdown_extensions:
    - admonition
    - codehilite
    - pymdownx.emoji:
        emoji_generator: !!python/name:pymdownx.emoji.to_svg

theme:
    name: material
    palette:
        primary: "light green"
        accent: "indigo"
    favicon: img/favicon.ico
    logo: img/favicon.ico
    
use_directory_urls: False

pages:
    - Home: index.md
    - Getting Started: getting-started.md
    - Solar Pi Apps: solar-pi-apps.md    
    - Hardware: hardware.md
    - Advanced Things:
        - Terminal: Advanced-Things/terminal.md
        - Linux Commands: Advanced-Things/commands.md
        - Python: Advanced-Things/python.md
        - Programming Glossary: Advanced-Things/programming-glossary.md