site_name: Solar Pi Docs

markdown_extensions:
    - admonition

theme:
    name: material
    palette:
        primary: "light green"
        accent: "indigo"
    favicon: img/favicon.ico
    logo: img/favicon.ico
    
use_directory_urls: False
pages:
    - Home: index.md
    - Get Started: Get Started.md
    - Raspbian: raspbian.md
    - Hardware: hardware.md
    - Advanced Things:
        - Linux Commands: Advanced Things/commands.md
        - Python: Advanced Things/python.md