#!/usr/bin/env python3

from appJar import gui
from subprocess import Popen

def LanguageHandler(press):
    if press == "English":
        with open("/etc/default/locale", "w") as file:
            file.write("#  File generated by update-locale\nLANG=en_GB.UTF-8")
            print("file written")
        with open("/usr/local/bin/Solar Pi/Solar Pi Welcome/language.txt", "w") as file:
            file.write("english")
        app.changeLanguage("english")

    elif press == "Español":
        with open("/etc/default/locale", "w") as file:
            file.write("#  File generated by update-locale\nLANG=es_ES.UTF-8")
            file.write("")
            print("file written")
        app.changeLanguage("spanish")
            
        with open("/usr/local/bin/Solar Pi/Solar Pi Welcome/language.txt", "w") as file:
            file.write("spanish")
            
    if app.yesNoBox("Reboot", "You need to reboot your Solar Pi to apply these changes.\nWould you like to reboot now?") == True:
        Popen("/usr/local/bin/Solar Pi/Resources/Launchers/Reboot.sh")          

with open("../Solar Pi Settings/Settings.ini") as file:
    data = file.readlines()[0]
    data = data.split(",")
    theme = data[3]

with gui("Languages", useTtk=True) as app:
    app.setResizable(False)

    if theme == "Solar Pi":
        custom = True
        app.setTtkTheme("plastik")
        app.setTtkTheme("clam")
        #app.ttkStyle.configure(".", font="10", background="white")

        # Highlighted button
        app.ttkStyle.configure("H.TButton", background="#324581", foreground="white", bordercolor="#687396")
        app.ttkStyle.map("H.TButton", background=[("pressed", "#172141"), ("active", "#4059a9")])

        # Regular button
        app.ttkStyle.configure("TButton", background="#dbdce2", bordercolor="#687396")

        # LabelFrame colour
        app.ttkStyle.configure("TLabelframe", bordercolor="#687396")

        app.setBg("white")

    else:
        custom = False
        app.setTtkTheme(theme)
        if theme != "black":
            app.ttkStyle.configure(".", background="white", foreground="black")
            app.setBg("white")

    app.setPadding(5, 5)
    with app.labelFrame("Languages"):
        app.setPadding(5, 5)
        app.setSticky("nesw")
        
        with app.labelFrame("English", 0, 0):
            app.setPadding(5, 5)
            app.addImage("uk_flag", "../Resources/Images/uk_flag.gif")
            app.addButton("English", LanguageHandler, 0, 1)
            
        with app.labelFrame("Español", 0, 1):
            app.setPadding(5, 5)
            app.addImage("spain_flag", "../Resources/Images/spain_flag.gif")
            app.addButton("Español", LanguageHandler, 0, 1)

    if custom == False:
        app.setLabelFrameStyle("Languages", "TFrame")
        app.setLabelFrameStyle("English", "TFrame")
        app.setLabelFrameStyle("Español", "TFrame")